config/routes.rb
Rails.application.routes.draw do
  root	'static_pages#test'
  get   '/test/load_car_makes', to: 'static_pages#load_car_makes'
  get   '/test/load_car_models', to: 'static_pages#load_car_models'
  get   '/test/load_region', to: 'static_pages#load_region'
  get   '/test/load_locate', to: 'static_pages#load_locate'
  get   '/test/load_pack', to: 'static_pages#load_pack'
  get   '/test/save', to: 'static_pages#test_save'
  get   '/test/mail', to: 'static_pages#test_mail'
  get   'test/load_promo', to: 'static_pages#load_promo'

  get   '/book/load_car_makes'  , to: 'bookings#load_car_makes'
  get   '/book/load_car_models' , to: 'bookings#load_car_models'
  get   '/book/load_region'     , to: 'bookings#load_region'
  get   '/book/load_locate'     , to: 'bookings#load_locate'
  get 	'/book'		, to: 'bookings#booking'
  post 	'/book'		, to: 'bookings#create'
  get 	'/mng'		, to: 'static_pages#management'
  get	  '/mngn'		, to: 'management#m_new'
  post  '/mngn'		, to: 'management#create'
  get	  '/cusn'		, to: 'customer#c_new'
  post  '/cusn'		, to: 'customer#create'
  get	  '/srvn'		, to: 'service_partner#s_new'
  post  '/srvn'		, to: 'service_partner#create'
  get 	'/signup'	, to: 'static_pages#s_signup'
  get 	'/login'	, to: 'static_pages#s_login'
  get   '/mngl'   , to:  'management#m_session'
  post  '/mngl'   , to: 'management#mngl'
  get   '/cusl'   , to:  'customer#c_session'
  post  '/cusl'   , to: 'customer#cusl'
  get   '/srvl'   , to:  'service_partner#s_session'
  post  'srvl'    , to: 'service_partner#srvl'
  get   '/logout' , to: 'management#destroy'
  get   '/book_mng',to: 'static_pages#booking_mng'
  delete '/del_pack', to: 'static_pages#destroy'
  get '/book/save_pack', to: 'static_pages#create'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def test
  end
  def load_promo
    promo = Promo.all
    respond_to do |format|
      format.json { render json: promo.to_json, status: :ok }
    end
  end
  def load_pack
    pack = Package.where(id:[1..5])
    respond_to do |format|
			format.json { render json: pack.to_json, status: :ok }
		end
  end
  def load_region
		mjloc = Mjloc.where(id:[1..5])
		respond_to do |format|
			format.json { render json: mjloc.to_json, status: :ok }
		end
	end
	def load_locate
		region = params["region"].to_i
		if region == 2
			mnloc = Mnloc.where(id:[1..2])
		end
		respond_to do |format|
			format.json { render json: mnloc.to_json, status: :ok }
		end
	end
	def load_car_makes
		option_no = params["option_no"].to_i
		if option_no == 2
				car_make = Make.where(id:[1,2,3])
		elsif option_no == 3
				car_make = Make.where(id:[1,2,3])
		elsif option_no == 4
				car_make = Make.where(id:[1,3])
		elsif option_no == 5
				car_make = Make.where(id:[1,4..10])
		else
				car_make = 0
		end
		respond_to do |format|
			format.json { render json: car_make.to_json, status: :ok }
		end
	end
	def load_car_models
		make_no = params["make_no"].to_i
		if make_no == 2
			car_model = Model.where(id:[1..18])
		elsif make_no == 3
			car_model = Model.where(id:[1,19..26])
		else
			car_model = 0
		end
		respond_to do |format|
			format.json { render json: car_model.to_json, status: :ok }
		end
	end
  def test_save
    name = params["name"]
    email = params["email"]
    phone = params["phone"]
    make = params["make"]
    modelv = params["model"]
    servicev = params["service"]
    region = params["region"]
    location = params["location"]
    date = params["date"]
    transfer = params["transfer"]
    cash = params["cash"]
    servicen = params["servicen"]
    maken = params["maken"]
    modeln = params["modeln"]
    regionn = params["regionn"]
    locationn = params["locationn"]
    promo = params["promo"]
    test_save = Test.create(name: name, email: email, phone: phone, make: make, model: modelv, region: region, service: servicev, location: location, date: date, transfer: transfer, cash: cash)
    BookingMailMailer.booking_mail(name, email, phone, servicen, maken, modeln, date, regionn, locationn, transfer, cash, promo).deliver_now
    respond_to do |format|
			format.json {render json: test_save.to_json, status: :ok }
		end
  end
  def booking_mng
    @package = Package.all
    @newpack = Package.new
    @make = Make.all
    @model = Model.all
  end
  def destroy
    @package = Package.find(params[:pack])
    @package.destroy
    flash[:success] = "Package Deleted"
    redirect_to book_mng_path
  end
  def create
    car1 = params["proton"]
    car2 = params["produa"]
    car3 = params["others"]
    pack = params["pack"]
    package = Package.create(name: pack, proton: car1, produa: car2, others: car3)
    package.save
    flash[:success] = "Package Created"
    redirect_to book_mng_path
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/booking.html.erb
<% provide(:title, "Booking") %>
<div class="center jumbotron">
		<h1>SERV Booking</h1>
		<p>Please fill in the form below with the correct information</p>
</div>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'shared/booking_form' %>
	</div>
</div>

app/views/static_pages/booking_mng.html.haml
- provide(:title, "Booking Management")
.row
  .col-md-8.col-md-offset-2
    %h1.center.jumbotron Booking Management
    %h4
      Package Setting |
      %button#create-user Create new package
      #dialog-form{:title => "Create new package"}
        %form
          %fieldset
            %label{:for => "package"} Package
            %input#package.text.ui-widget-content.ui-corner-all{:name => "package", :type => "text"}
            %label{:for => "make"} Car Make
            .car_make
              %label
                %input#proton{:name => "proton", :type => "checkbox", onclick: "proton_sel()"}
                Proton
                %input#produa{:name => "produa", :type => "checkbox", onclick: "produa_sel()"}
                Produa
                %input#others{:name => "others", :type => "checkbox", onclick: "others_sel()"}
                Others
    %hr/
    %ul#packli
      - @package.each do |pack|
        - if pack.id == 1
        - else
          %li
            = pack.name
            | #{link_to "Delete", del_pack_path(:pack => pack.id), method: :delete, data: {confirm: "Confirm package deletion?"}}
    %h4 Supported Car Make
    %hr/
    %ul
      - @make.each do |pack|
        %li
          = pack.id
          | #{pack.name}
    %h4 Supported Car Model
    %hr/
    %ul
      - @model.each do |pack|
        %li
          = pack.make_id
          | #{pack.name}

app/views/static_pages/customer.html.erb
<% provide(:title, current_user.name) %>
<h1>
	<%= current_user.name %>
</h1>
<p>
	Customer dashboard content
<p>

app/views/static_pages/home.html.erb
<h1>Homepage</h1>
<p>Homepage details</p> 

app/views/static_pages/management.html.erb
<% provide(:title, "Management") %>
<div class="center jumbotron">
		<h1>SERV Management</h1>
</div>
<div class="container">
	<nav>
		<ul class="nav navbar-nav  navbar-right">
			<li><%= link_to "Service Partner", '#' %></li>
			<li><%= link_to "Access Level Setting", '#' %></li>
			<li><%= link_to "Booking Setting", book_mng_path %></li>
		</ul>
	</nav>
</div>
<div class="col-md-8">
	<h2>Management Dashboard</h2>
</div>

app/views/static_pages/s_login.html.erb
<% provide(:title, "Login Selection") %>
<div class="center jumbotron">
	<h1>Please select login category</h1>
	<h2><%= link_to 'As admin', mngl_path, class: "btn btn-primary" %></h2>
	<h2><%= link_to 'As customer', cusl_path, class: "btn btn-primary" %></h2>
	<h2><%= link_to 'As service partner', srvl_path, class: "btn btn-primary" %></h2>
</div>

app/views/static_pages/s_signup.html.erb
<% provide(:title, "Signup Selection") %>
<div class="center jumbotron">
	<h1>Please select signup category</h1>
	<h2><%= link_to 'As admin', mngn_path, class: "btn btn-primary" %></h2>
	<h2><%= link_to 'As customer', cusn_path, class: "btn btn-primary" %></h2>
	<h2><%= link_to 'As service partner', srvn_path, class: "btn btn-primary" %></h2>
</div>

app/views/static_pages/service.html.erb
<% provide(:title, current_user.name) %>
<h1>
	<%= current_user.name %>
</h1>
<p>
	Service Partner dashboard content
<p>