config/routes.rb
Rails.application.routes.draw do
  root	'static_pages#test'
  get   '/test/load_car_makes', to: 'static_pages#load_car_makes'
  get   '/test/load_car_models', to: 'static_pages#load_car_models'
  get   '/test/load_region', to: 'static_pages#load_region'
  get   '/test/load_locate', to: 'static_pages#load_locate'
  get   '/test/load_pack', to: 'static_pages#load_pack'
  get   '/test/save', to: 'static_pages#test_save'
  get   '/test/mail', to: 'static_pages#test_mail'
  get   'test/load_promo', to: 'static_pages#load_promo'

  get   '/book/load_car_makes'  , to: 'bookings#load_car_makes'
  get   '/book/load_car_models' , to: 'bookings#load_car_models'
  get   '/book/load_region'     , to: 'bookings#load_region'
  get   '/book/load_locate'     , to: 'bookings#load_locate'
  get 	'/book'		, to: 'bookings#booking'
  post 	'/book'		, to: 'bookings#create'
  get 	'/mng'		, to: 'static_pages#management'
  get	  '/mngn'		, to: 'management#m_new'
  post  '/mngn'		, to: 'management#create'
  get	  '/cusn'		, to: 'customer#c_new'
  post  '/cusn'		, to: 'customer#create'
  get	  '/srvn'		, to: 'service_partner#s_new'
  post  '/srvn'		, to: 'service_partner#create'
  get 	'/signup'	, to: 'static_pages#s_signup'
  get 	'/login'	, to: 'static_pages#s_login'
  get   '/mngl'   , to:  'management#m_session'
  post  '/mngl'   , to: 'management#mngl'
  get   '/cusl'   , to:  'customer#c_session'
  post  '/cusl'   , to: 'customer#cusl'
  get   '/srvl'   , to:  'service_partner#s_session'
  post  'srvl'    , to: 'service_partner#srvl'
  get   '/logout' , to: 'management#destroy'
  get   '/book_mng',to: 'static_pages#booking_mng'
  delete '/del_pack', to: 'static_pages#destroy'
  get '/book/save_pack', to: 'static_pages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_one :model
  has_one :mnloc
  before_save {email.downcase!}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true, length: {maximum: 50}
  validates :phone_no, presence: true
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}
end

app/models/customer.rb
class Customer < ApplicationRecord
	before_save {email.downcase!}
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum: 6}, allow_nil: true
end

app/models/make.rb
class Make < ApplicationRecord
    has_many :model, dependent: :destroy
end

app/models/management.rb
class Management < ApplicationRecord
	before_save {email.downcase!}
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum: 6}, allow_nil: true
end

app/models/mjloc.rb
class Mjloc < ApplicationRecord
  has_many :mnloc
end

app/models/mnloc.rb
class Mnloc < ApplicationRecord
end

app/models/model.rb
class Model < ApplicationRecord
end

app/models/package.rb
class Package < ApplicationRecord
 cattr_accessor :proton, :produa, :others
end

app/models/promo.rb
class Promo < ApplicationRecord
end

app/models/service_partner.rb
class ServicePartner < ApplicationRecord
	before_save {email.downcase!}
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum: 6}, allow_nil: true
end

app/models/test.rb
class Test < ApplicationRecord
  validates :name, presence: true
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def l_new
	end
	def create
		admin = Management.find_by(email: params[:session][:email].downcase)
		cust = Customer.find_by(email: params[:session][:email].downcase)
		serv = ServicePartner.find_by(email: params[:session][:email].downcase)

		if admin && admin.authenticate(params[:session][:password])
			login admin
			current_user (params[:session][:email].downcase)
			flash[:success] = "Logged in as Admin"
			redirect_to root_url
		elsif serv && serv.authenticate(params[:session][:password])
			login serv
			flash[:success] = "Logged in as Service Partner"
			redirect_to root_url
		elsif cust && cust.authenticate(params[:session][:password])
			login cust
			flash[:success] = "Logged in as Customer"
			redirect_to root_url
		else
			flash.now[:danger] = 'Invalid email/password'
			render 'l_new'
		end
	end
	def destroy
		logout
		redirect_to root_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "SERV"
		if page_title.empty?
			base_title
		else
		 	page_title + " | " + base_title
		end
	end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/management_helper.rb
module ManagementHelper
end

app/helpers/service_partner_helper.rb
module ServicePartnerHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def logout
	   session.delete(:user_id)
	   @current_user = nil
     @status = nil
     @admin = nil
  end
  def loginm(user)
	   session[:user_id]= user.id
     session[:status]= user.status
     session[:admin]= user.status
  end
  def mcurrent_user
    @current_user ||= Management.find_by(id: session[:user_id])
  end
  def loginc(user)
     session[:user_id]= user.id
  end
  def ccurrent_user
    @current_user ||= Customer.find_by(id: session[:user_id])
  end
  def logged_in?
    if $log == 1
      !mcurrent_user.nil?
    elsif $log == 2
      !ccurrent_user.nil?
    else
      return false
    end
  end
  def admin?
    if $log == 1
      @current_user.admin?
    elsif $log == 2
      @current_user.admin?
    else
      return false
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "SERV", root_url, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Booking", book_path %></li>
				<% if logged_in? %>
					<% if admin? %>
						<li><%= link_to "Management", mng_path %></li>
					<% end %>
					<li><%= link_to "Logout", logout_path %></li>
				<% else %>
					<li><%= link_to "Login", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_include.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src='https://www.google.com/recaptcha/api.js'></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/include' %>
  </head>

  <body>
	<%= render 'layouts/header' %>
  <h2>Value:<%= @current_user %></h2>
	<%= flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_booking_form.html.haml
= form_for(@booking, url: book_path) do |f|
  = render 'shared/error_messages', object: f.object
  = f.label :name
  = f.text_field :name, placeholder: "Name", class: 'form-control'
  = f.label "Phone Number"
  = f.text_field :phone_no, class: 'form-control', placeholder: "Phone Number", onchange: "console.log(this.val)"
  = f.label :email
  = f.email_field :email, placeholder: "Email", class: 'form-control'
  = f.label :booking_date
  = f.text_field :prefered_booking_date, placeholder: "Select a Booking Date", onchange:'date_select()'
  = f.label "Region"
  %select#region{onchange:"load_locate($(this).val())"}
  .sloc
    = f.label "Location"
    = f.select :location_id, ['...loading']
  = f.label :package
  = f.select :package, options_from_collection_for_select(@package, "id", "name"), {class: 'form-control'}, :onchange => "load_car_makes($(this).val());"
  .car_makes
    = f.label "Car Make"
    %select#car_makes{onchange:"load_car_models($(this).val())"}
  .car_models
    = f.label "Car Model"
    = f.select :model_id, ['...loading']
  .g-recaptcha{"data-sitekey" => "6LcXOioUAAAAAHX-M1So3YLi0lSRKuf9gGv4qF5F"}

  = f.submit "Send Booking Infromation", class: "btn btn-primary"

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div class id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/simple_captcha/_simple_captcha.erb
<style type="text/css">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>

  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>

  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>

  <div class='simple_captcha_refresh_button'>
    <%= simple_captcha_options[:refresh_button] %>
  </div>
</div>